// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwoOABv2u8BCHsjHPXH0wEVZtWC9dDXU',
    appId: '1:148491058747:web:5d15134dfc7b071adee61e',
    messagingSenderId: '148491058747',
    projectId: 'quizzler-play-ai',
    authDomain: 'quizzler-play-ai.firebaseapp.com',
    storageBucket: 'quizzler-play-ai.firebasestorage.app',
    measurementId: 'G-17XC2DM57W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZEAAqpqD8cNpQwfmO3FGBvRP_UANesIE',
    appId: '1:148491058747:android:95b13467ec3676f2dee61e',
    messagingSenderId: '148491058747',
    projectId: 'quizzler-play-ai',
    storageBucket: 'quizzler-play-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsnoCeSLjmo3gQqUP7Chiuu_-ot6mId8',
    appId: '1:148491058747:ios:21131247f7390ef9dee61e',
    messagingSenderId: '148491058747',
    projectId: 'quizzler-play-ai',
    storageBucket: 'quizzler-play-ai.firebasestorage.app',
    iosBundleId: 'com.quizzler.quizzler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOsnoCeSLjmo3gQqUP7Chiuu_-ot6mId8',
    appId: '1:148491058747:ios:21131247f7390ef9dee61e',
    messagingSenderId: '148491058747',
    projectId: 'quizzler-play-ai',
    storageBucket: 'quizzler-play-ai.firebasestorage.app',
    iosBundleId: 'com.quizzler.quizzler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwwoOABv2u8BCHsjHPXH0wEVZtWC9dDXU',
    appId: '1:148491058747:web:e3782115a76a023fdee61e',
    messagingSenderId: '148491058747',
    projectId: 'quizzler-play-ai',
    authDomain: 'quizzler-play-ai.firebaseapp.com',
    storageBucket: 'quizzler-play-ai.firebasestorage.app',
    measurementId: 'G-CY35MHZV85',
  );
}
